<hr>
<?php 
$listIngredient = $block->getIngredientCollection();
$productCollection = $block->getProductById();
foreach ($productCollection as $product) { 
     $ingredientId = $product->getIngredient_attribute();  
}
$arrayId = explode(',', $ingredientId);
$listIngredient->addFieldToFilter('entity_id', array('in' => $arrayId));
foreach ($listIngredient as $value) {
	?>
	<div style="text-align: center; float: left;margin-left: 10px">
		<img src="<?php echo $block->getUrlImage().$value->getImage();?>" width="54" height="54"  />
		<br>
		<?php  echo $value->getName(); ?>
	</div>
<?php
	}
?>